apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-environments-test
spec:
  generators:
    - git:
        repoURL: https://github.com/lbac-redhat/argocd-poc
        revision: main
        files:
          - path: "appset/**/helmValues.yml"
  template:
    metadata:
      name: '{{ path.basename }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: '{{ path.basename }}'
        server: https://kubernetes.default.svc
      project: default
      source:
        helm:
          values: |
            namespace_name: '{{ path.basename }}'
            {{ values }}
        path: environment
        repoURL: https://github.com/lbac-redhat/helmcharts-poc.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
