apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env-appofapps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/
    repoURL: https://github.com/lbac-redhat/argocd-poc.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
