apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: env1
  namespace: openshift-gitops
spec:
  destination:
    namespace: env1
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        size: medium
        adminGroupName: test-group
    path: environment
    repoURL: https://github.com/lbac-redhat/helmcharts-poc.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
